export const LIST_ALL = 'LIST_ALL'
export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const GET_TASK = 'GET_TASK'
export const SHOW_FORM = 'SHOW_FORM'
export const CLOSE_FORM = 'CLOSE_FORM'
export const OPEN_FORM = 'OPEN_FORM'
export const EDIT_TASK = 'EDIT_TASK'
export const CLEAR_DATA = 'CLEAR_DATA'
export const SEARCH_DATA = 'SEARCH_DATA'
export const FILTER_DATA = 'FILTER_DATA'
export const RESET_DATA = 'RESET_DATA'

